- name: Set hostname to inventory name
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

- name: Install base packages + nginx
  ansible.builtin.apt:
    name:
      - net-tools
      - dnsutils
      - wget
      - curl
      - mc
      - rsync
      - nginx
    state: present
    update_cache: yes
